name: Build 01_aks_python_server Docker Image and Push to ACR

on:
  push:
    branches: ["main"]
    paths:
      - "01_aks_python_server/**"   # 只要这个目录有变动才触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Container Registry Login
        uses: azure/docker-login@v2
        with:
            login-server: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}
            username: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
            password: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}


      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./01_aks_python_server
          file: ./01_aks_python_server/docker/Dockerfile
          push: true
          tags: |
            ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/01_aks_python_server:latest
            ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/01_aks_python_server:${{ github.sha }}